[package]
name = "framework"
version = "0.0.0"
edition = "2021"

[dependencies]
telegram_macros = { path = "../macros" }
telegram_bots_api = { path = "../../../telegram_bots_api", features = ["sync", "async"] }
#telegram_bots_api = { version = "0.72.0", features = ["all"] }

[[example]]
name = "playground"
path = "examples/playground.rs"
