[package]
name = "telegram_framework"
version = "0.0.0"
edition = "2021"

[dependencies]
telegram_bots_api = { version = "0.73.2", features = ["all"] }
telegram_macros = { path = "../macros" }
proc-macro-error = "1.0.4"
serde = { version = "1.0.199", features = ["derive"] }

[dev-dependencies]

[[example]]
name = "playground"
path = "examples/playground.rs"
