[package]
name = "telegram_framework"
version = "0.0.0"
edition = "2021"

[dependencies]
telegram_bots_api = { path = "../../../telegram_bots_api", features = ["sync", "async"] }
#telegram_bots_api = { version = "0.72.0", features = ["all"] }
telegram_macros = { path = "../macros" }
proc-macro-error = "1.0.4"

[dev-dependencies]

[[example]]
name = "playground"
path = "examples/playground.rs"
