pub mod animation;
pub mod audio;
mod business;
pub mod chat_actions;
pub mod commands;
pub mod contact;
pub mod dice;
pub mod document;
pub mod file;
pub mod game;
pub mod location;
mod media_group;
mod menu_button;
pub mod my;
pub mod passport;
pub mod photo;
pub mod poll;
pub mod pooling;
mod user;
pub mod venue;
pub mod video;
pub mod video_note;
pub mod voice;
pub mod webhook;
